package mc.thehealingangel.hiraeth_spirits.client.model.antler;

import mc.thehealingangel.hiraeth_spirits.HiraethSpirits;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;

public class ModelAntlers4 extends ModelBase
{
    private static final ResourceLocation TEXTURE = new ResourceLocation(HiraethSpirits.MOD_ID, "textures/antlers/antlers_4.png");
    public ModelRenderer bit1;
    public ModelRenderer bit2;
    public ModelRenderer bit3;
    public ModelRenderer bridge1;
    public ModelRenderer bit4;
    public ModelRenderer bit5;
    public ModelRenderer bridge2;
    public ModelRenderer bit6;
    public ModelRenderer bit7;
    public ModelRenderer bridgeVertical;
    public ModelRenderer bit8;
    public ModelRenderer bit9;
    public ModelRenderer bit10;
    public ModelRenderer bit11;
    public ModelRenderer bit12;
    public ModelRenderer bit13;
    public ModelRenderer bit1_1;
    public ModelRenderer bit2_1;
    public ModelRenderer bit3_1;
    public ModelRenderer bridge1_1;
    public ModelRenderer bit4_1;
    public ModelRenderer bit5_1;
    public ModelRenderer bridge2_1;
    public ModelRenderer bit6_1;
    public ModelRenderer bit7_1;
    public ModelRenderer bridgeVertical_1;
    public ModelRenderer bit8_1;
    public ModelRenderer bit9_1;
    public ModelRenderer bit10_1;
    public ModelRenderer bit11_1;
    public ModelRenderer bit12_1;
    public ModelRenderer bit13_1;

    public ModelAntlers4()
    {
        this.textureWidth = 16;
        this.textureHeight = 16;
        this.bit1_1 = new ModelRenderer(this, 0, 0);
        this.bit1_1.setRotationPoint(4.0F, -4.0F, -0.95F);
        this.bit1_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit13_1 = new ModelRenderer(this, 8, 10);
        this.bit13_1.setRotationPoint(5.2F, -9.8F, -0.75F);
        this.bit13_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit2 = new ModelRenderer(this, 4, 0);
        this.bit2.setRotationPoint(-5.5F, -3.5F, -1.0F);
        this.bit2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit11 = new ModelRenderer(this, 8, 8);
        this.bit11.setRotationPoint(-7.2F, -8.7F, -0.85F);
        this.bit11.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit6_1 = new ModelRenderer(this, 6, 4);
        this.bit6_1.setRotationPoint(8.5F, -6.7F, -0.95F);
        this.bit6_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit3 = new ModelRenderer(this, 8, 0);
        this.bit3.setRotationPoint(-5.5F, -5.0F, -1.0F);
        this.bit3.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit12_1 = new ModelRenderer(this, 4, 10);
        this.bit12_1.setRotationPoint(5.7F, -9.4F, -0.8F);
        this.bit12_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bridgeVertical = new ModelRenderer(this, 0, 6);
        this.bridgeVertical.setRotationPoint(-8.2F, -7.7F, -0.95F);
        this.bridgeVertical.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1, 0.0F);
        this.bridge1_1 = new ModelRenderer(this, 0, 2);
        this.bridge1_1.setRotationPoint(5.0F, -5.6F, -1.05F);
        this.bridge1_1.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.bit9_1 = new ModelRenderer(this, 8, 6);
        this.bit9_1.setRotationPoint(8.25F, -9.2F, -0.95F);
        this.bit9_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bridgeVertical_1 = new ModelRenderer(this, 0, 6);
        this.bridgeVertical_1.setRotationPoint(7.2F, -7.7F, -0.95F);
        this.bridgeVertical_1.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1, 0.0F);
        this.bit1 = new ModelRenderer(this, 0, 0);
        this.bit1.setRotationPoint(-5.0F, -4.0F, -0.95F);
        this.bit1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit5 = new ModelRenderer(this, 10, 2);
        this.bit5.setRotationPoint(-6.0F, -7.0F, -0.95F);
        this.bit5.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit6 = new ModelRenderer(this, 6, 4);
        this.bit6.setRotationPoint(-9.5F, -6.7F, -0.95F);
        this.bit6.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit4_1 = new ModelRenderer(this, 6, 2);
        this.bit4_1.setRotationPoint(4.5F, -6.4F, -1.0F);
        this.bit4_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit5_1 = new ModelRenderer(this, 10, 2);
        this.bit5_1.setRotationPoint(5.0F, -7.0F, -0.95F);
        this.bit5_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit3_1 = new ModelRenderer(this, 8, 0);
        this.bit3_1.setRotationPoint(4.5F, -5.0F, -1.0F);
        this.bit3_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit11_1 = new ModelRenderer(this, 8, 8);
        this.bit11_1.setRotationPoint(6.2F, -8.7F, -0.85F);
        this.bit11_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit8 = new ModelRenderer(this, 4, 6);
        this.bit8.setRotationPoint(-8.75F, -8.7F, -1.0F);
        this.bit8.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit2_1 = new ModelRenderer(this, 4, 0);
        this.bit2_1.setRotationPoint(4.5F, -3.5F, -1.0F);
        this.bit2_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit4 = new ModelRenderer(this, 6, 2);
        this.bit4.setRotationPoint(-5.5F, -6.4F, -1.0F);
        this.bit4.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bridge1 = new ModelRenderer(this, 0, 2);
        this.bridge1.setRotationPoint(-7.0F, -5.6F, -1.05F);
        this.bridge1.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.bit12 = new ModelRenderer(this, 4, 10);
        this.bit12.setRotationPoint(-6.7F, -9.4F, -0.8F);
        this.bit12.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit8_1 = new ModelRenderer(this, 4, 6);
        this.bit8_1.setRotationPoint(7.75F, -8.7F, -1.0F);
        this.bit8_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bridge2_1 = new ModelRenderer(this, 0, 4);
        this.bridge2_1.setRotationPoint(6.5F, -6.2F, -1.0F);
        this.bridge2_1.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.bit7 = new ModelRenderer(this, 10, 4);
        this.bit7.setRotationPoint(-10.0F, -7.3F, -0.9F);
        this.bit7.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit7_1 = new ModelRenderer(this, 10, 4);
        this.bit7_1.setRotationPoint(9.0F, -7.3F, -0.9F);
        this.bit7_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit13 = new ModelRenderer(this, 8, 10);
        this.bit13.setRotationPoint(-6.2F, -9.8F, -0.75F);
        this.bit13.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit10 = new ModelRenderer(this, 4, 8);
        this.bit10.setRotationPoint(-7.5F, -8.0F, -0.9F);
        this.bit10.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bit10_1 = new ModelRenderer(this, 4, 8);
        this.bit10_1.setRotationPoint(6.5F, -8.0F, -0.9F);
        this.bit10_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.bridge2 = new ModelRenderer(this, 0, 4);
        this.bridge2.setRotationPoint(-8.5F, -6.2F, -1.0F);
        this.bridge2.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.bit9 = new ModelRenderer(this, 8, 6);
        this.bit9.setRotationPoint(-9.25F, -9.2F, -0.95F);
        this.bit9.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        Minecraft.getMinecraft().getTextureManager().bindTexture(TEXTURE);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit1_1.offsetX, this.bit1_1.offsetY, this.bit1_1.offsetZ);
        GlStateManager.translate(this.bit1_1.rotationPointX * f5, this.bit1_1.rotationPointY * f5, this.bit1_1.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.9D);
        GlStateManager.translate(-this.bit1_1.offsetX, -this.bit1_1.offsetY, -this.bit1_1.offsetZ);
        GlStateManager.translate(-this.bit1_1.rotationPointX * f5, -this.bit1_1.rotationPointY * f5, -this.bit1_1.rotationPointZ * f5);
        this.bit1_1.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit13_1.offsetX, this.bit13_1.offsetY, this.bit13_1.offsetZ);
        GlStateManager.translate(this.bit13_1.rotationPointX * f5, this.bit13_1.rotationPointY * f5, this.bit13_1.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.5D);
        GlStateManager.translate(-this.bit13_1.offsetX, -this.bit13_1.offsetY, -this.bit13_1.offsetZ);
        GlStateManager.translate(-this.bit13_1.rotationPointX * f5, -this.bit13_1.rotationPointY * f5, -this.bit13_1.rotationPointZ * f5);
        this.bit13_1.render(f5);
        GlStateManager.popMatrix();
        this.bit2.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit11.offsetX, this.bit11.offsetY, this.bit11.offsetZ);
        GlStateManager.translate(this.bit11.rotationPointX * f5, this.bit11.rotationPointY * f5, this.bit11.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.7D);
        GlStateManager.translate(-this.bit11.offsetX, -this.bit11.offsetY, -this.bit11.offsetZ);
        GlStateManager.translate(-this.bit11.rotationPointX * f5, -this.bit11.rotationPointY * f5, -this.bit11.rotationPointZ * f5);
        this.bit11.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit6_1.offsetX, this.bit6_1.offsetY, this.bit6_1.offsetZ);
        GlStateManager.translate(this.bit6_1.rotationPointX * f5, this.bit6_1.rotationPointY * f5, this.bit6_1.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.9D);
        GlStateManager.translate(-this.bit6_1.offsetX, -this.bit6_1.offsetY, -this.bit6_1.offsetZ);
        GlStateManager.translate(-this.bit6_1.rotationPointX * f5, -this.bit6_1.rotationPointY * f5, -this.bit6_1.rotationPointZ * f5);
        this.bit6_1.render(f5);
        GlStateManager.popMatrix();
        this.bit3.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit12_1.offsetX, this.bit12_1.offsetY, this.bit12_1.offsetZ);
        GlStateManager.translate(this.bit12_1.rotationPointX * f5, this.bit12_1.rotationPointY * f5, this.bit12_1.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.6D);
        GlStateManager.translate(-this.bit12_1.offsetX, -this.bit12_1.offsetY, -this.bit12_1.offsetZ);
        GlStateManager.translate(-this.bit12_1.rotationPointX * f5, -this.bit12_1.rotationPointY * f5, -this.bit12_1.rotationPointZ * f5);
        this.bit12_1.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bridgeVertical.offsetX, this.bridgeVertical.offsetY, this.bridgeVertical.offsetZ);
        GlStateManager.translate(this.bridgeVertical.rotationPointX * f5, this.bridgeVertical.rotationPointY * f5, this.bridgeVertical.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.9D);
        GlStateManager.translate(-this.bridgeVertical.offsetX, -this.bridgeVertical.offsetY, -this.bridgeVertical.offsetZ);
        GlStateManager.translate(-this.bridgeVertical.rotationPointX * f5, -this.bridgeVertical.rotationPointY * f5, -this.bridgeVertical.rotationPointZ * f5);
        this.bridgeVertical.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bridge1_1.offsetX, this.bridge1_1.offsetY, this.bridge1_1.offsetZ);
        GlStateManager.translate(this.bridge1_1.rotationPointX * f5, this.bridge1_1.rotationPointY * f5, this.bridge1_1.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 1.1D);
        GlStateManager.translate(-this.bridge1_1.offsetX, -this.bridge1_1.offsetY, -this.bridge1_1.offsetZ);
        GlStateManager.translate(-this.bridge1_1.rotationPointX * f5, -this.bridge1_1.rotationPointY * f5, -this.bridge1_1.rotationPointZ * f5);
        this.bridge1_1.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit9_1.offsetX, this.bit9_1.offsetY, this.bit9_1.offsetZ);
        GlStateManager.translate(this.bit9_1.rotationPointX * f5, this.bit9_1.rotationPointY * f5, this.bit9_1.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.9D);
        GlStateManager.translate(-this.bit9_1.offsetX, -this.bit9_1.offsetY, -this.bit9_1.offsetZ);
        GlStateManager.translate(-this.bit9_1.rotationPointX * f5, -this.bit9_1.rotationPointY * f5, -this.bit9_1.rotationPointZ * f5);
        this.bit9_1.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bridgeVertical_1.offsetX, this.bridgeVertical_1.offsetY, this.bridgeVertical_1.offsetZ);
        GlStateManager.translate(this.bridgeVertical_1.rotationPointX * f5, this.bridgeVertical_1.rotationPointY * f5, this.bridgeVertical_1.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.9D);
        GlStateManager.translate(-this.bridgeVertical_1.offsetX, -this.bridgeVertical_1.offsetY, -this.bridgeVertical_1.offsetZ);
        GlStateManager.translate(-this.bridgeVertical_1.rotationPointX * f5, -this.bridgeVertical_1.rotationPointY * f5, -this.bridgeVertical_1.rotationPointZ * f5);
        this.bridgeVertical_1.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit1.offsetX, this.bit1.offsetY, this.bit1.offsetZ);
        GlStateManager.translate(this.bit1.rotationPointX * f5, this.bit1.rotationPointY * f5, this.bit1.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.9D);
        GlStateManager.translate(-this.bit1.offsetX, -this.bit1.offsetY, -this.bit1.offsetZ);
        GlStateManager.translate(-this.bit1.rotationPointX * f5, -this.bit1.rotationPointY * f5, -this.bit1.rotationPointZ * f5);
        this.bit1.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit5.offsetX, this.bit5.offsetY, this.bit5.offsetZ);
        GlStateManager.translate(this.bit5.rotationPointX * f5, this.bit5.rotationPointY * f5, this.bit5.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.9D);
        GlStateManager.translate(-this.bit5.offsetX, -this.bit5.offsetY, -this.bit5.offsetZ);
        GlStateManager.translate(-this.bit5.rotationPointX * f5, -this.bit5.rotationPointY * f5, -this.bit5.rotationPointZ * f5);
        this.bit5.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit6.offsetX, this.bit6.offsetY, this.bit6.offsetZ);
        GlStateManager.translate(this.bit6.rotationPointX * f5, this.bit6.rotationPointY * f5, this.bit6.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.9D);
        GlStateManager.translate(-this.bit6.offsetX, -this.bit6.offsetY, -this.bit6.offsetZ);
        GlStateManager.translate(-this.bit6.rotationPointX * f5, -this.bit6.rotationPointY * f5, -this.bit6.rotationPointZ * f5);
        this.bit6.render(f5);
        GlStateManager.popMatrix();
        this.bit4_1.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit5_1.offsetX, this.bit5_1.offsetY, this.bit5_1.offsetZ);
        GlStateManager.translate(this.bit5_1.rotationPointX * f5, this.bit5_1.rotationPointY * f5, this.bit5_1.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.9D);
        GlStateManager.translate(-this.bit5_1.offsetX, -this.bit5_1.offsetY, -this.bit5_1.offsetZ);
        GlStateManager.translate(-this.bit5_1.rotationPointX * f5, -this.bit5_1.rotationPointY * f5, -this.bit5_1.rotationPointZ * f5);
        this.bit5_1.render(f5);
        GlStateManager.popMatrix();
        this.bit3_1.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit11_1.offsetX, this.bit11_1.offsetY, this.bit11_1.offsetZ);
        GlStateManager.translate(this.bit11_1.rotationPointX * f5, this.bit11_1.rotationPointY * f5, this.bit11_1.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.7D);
        GlStateManager.translate(-this.bit11_1.offsetX, -this.bit11_1.offsetY, -this.bit11_1.offsetZ);
        GlStateManager.translate(-this.bit11_1.rotationPointX * f5, -this.bit11_1.rotationPointY * f5, -this.bit11_1.rotationPointZ * f5);
        this.bit11_1.render(f5);
        GlStateManager.popMatrix();
        this.bit8.render(f5);
        this.bit2_1.render(f5);
        this.bit4.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bridge1.offsetX, this.bridge1.offsetY, this.bridge1.offsetZ);
        GlStateManager.translate(this.bridge1.rotationPointX * f5, this.bridge1.rotationPointY * f5, this.bridge1.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 1.1D);
        GlStateManager.translate(-this.bridge1.offsetX, -this.bridge1.offsetY, -this.bridge1.offsetZ);
        GlStateManager.translate(-this.bridge1.rotationPointX * f5, -this.bridge1.rotationPointY * f5, -this.bridge1.rotationPointZ * f5);
        this.bridge1.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit12.offsetX, this.bit12.offsetY, this.bit12.offsetZ);
        GlStateManager.translate(this.bit12.rotationPointX * f5, this.bit12.rotationPointY * f5, this.bit12.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.6D);
        GlStateManager.translate(-this.bit12.offsetX, -this.bit12.offsetY, -this.bit12.offsetZ);
        GlStateManager.translate(-this.bit12.rotationPointX * f5, -this.bit12.rotationPointY * f5, -this.bit12.rotationPointZ * f5);
        this.bit12.render(f5);
        GlStateManager.popMatrix();
        this.bit8_1.render(f5);
        this.bridge2_1.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit7.offsetX, this.bit7.offsetY, this.bit7.offsetZ);
        GlStateManager.translate(this.bit7.rotationPointX * f5, this.bit7.rotationPointY * f5, this.bit7.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.8D);
        GlStateManager.translate(-this.bit7.offsetX, -this.bit7.offsetY, -this.bit7.offsetZ);
        GlStateManager.translate(-this.bit7.rotationPointX * f5, -this.bit7.rotationPointY * f5, -this.bit7.rotationPointZ * f5);
        this.bit7.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit7_1.offsetX, this.bit7_1.offsetY, this.bit7_1.offsetZ);
        GlStateManager.translate(this.bit7_1.rotationPointX * f5, this.bit7_1.rotationPointY * f5, this.bit7_1.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.8D);
        GlStateManager.translate(-this.bit7_1.offsetX, -this.bit7_1.offsetY, -this.bit7_1.offsetZ);
        GlStateManager.translate(-this.bit7_1.rotationPointX * f5, -this.bit7_1.rotationPointY * f5, -this.bit7_1.rotationPointZ * f5);
        this.bit7_1.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit13.offsetX, this.bit13.offsetY, this.bit13.offsetZ);
        GlStateManager.translate(this.bit13.rotationPointX * f5, this.bit13.rotationPointY * f5, this.bit13.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.5D);
        GlStateManager.translate(-this.bit13.offsetX, -this.bit13.offsetY, -this.bit13.offsetZ);
        GlStateManager.translate(-this.bit13.rotationPointX * f5, -this.bit13.rotationPointY * f5, -this.bit13.rotationPointZ * f5);
        this.bit13.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit10.offsetX, this.bit10.offsetY, this.bit10.offsetZ);
        GlStateManager.translate(this.bit10.rotationPointX * f5, this.bit10.rotationPointY * f5, this.bit10.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.8D);
        GlStateManager.translate(-this.bit10.offsetX, -this.bit10.offsetY, -this.bit10.offsetZ);
        GlStateManager.translate(-this.bit10.rotationPointX * f5, -this.bit10.rotationPointY * f5, -this.bit10.rotationPointZ * f5);
        this.bit10.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit10_1.offsetX, this.bit10_1.offsetY, this.bit10_1.offsetZ);
        GlStateManager.translate(this.bit10_1.rotationPointX * f5, this.bit10_1.rotationPointY * f5, this.bit10_1.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.8D);
        GlStateManager.translate(-this.bit10_1.offsetX, -this.bit10_1.offsetY, -this.bit10_1.offsetZ);
        GlStateManager.translate(-this.bit10_1.rotationPointX * f5, -this.bit10_1.rotationPointY * f5, -this.bit10_1.rotationPointZ * f5);
        this.bit10_1.render(f5);
        GlStateManager.popMatrix();
        this.bridge2.render(f5);
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.bit9.offsetX, this.bit9.offsetY, this.bit9.offsetZ);
        GlStateManager.translate(this.bit9.rotationPointX * f5, this.bit9.rotationPointY * f5, this.bit9.rotationPointZ * f5);
        GlStateManager.scale(1.0D, 1.0D, 0.9D);
        GlStateManager.translate(-this.bit9.offsetX, -this.bit9.offsetY, -this.bit9.offsetZ);
        GlStateManager.translate(-this.bit9.rotationPointX * f5, -this.bit9.rotationPointY * f5, -this.bit9.rotationPointZ * f5);
        this.bit9.render(f5);
        GlStateManager.popMatrix();
    }
}
